---
title: "citibike_predict_2015"
author: "Adnan Hoq"
date: "7/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r citibike data}
# define a function to turn strings into datetimes

parse_datetime <- function(s, format="%Y-%m-%d %H:%M:%S") {

  as.POSIXct(as.character(s), format=format)

}



# load each month of the trip data into one big data frame

csvs <- Sys.glob('*-tripdata.csv')

trips <- data.frame()



for (csv in csvs) {

  print(csv)

  tmp <- read_csv(csv, na='\\N')



  # the date format changed to something ugly in 2014-09 which read_csv doesn't recognize as a datetime,

  # so manually convert the date from a string to a datetime

  if (typeof(tmp$starttime) == "character")

    tmp <- mutate(tmp,

                  starttime=parse_datetime(starttime, "%m/%d/%Y %H:%M"),

                  stoptime=parse_datetime(stoptime, "%m/%d/%Y %H:%M"))



  trips <- rbind(trips, tmp)

}



# replace spaces in column names with underscores

names(trips) <- gsub(' ', '_', names(trips))



# add a column for year/month/day (without time of day)

trips <- mutate(trips, ymd=as.Date(starttime))



# recode gender as a factor 0->"Unknown", 1->"Male", 2->"Female"

trips <- mutate(trips, gender=factor(gender, levels=c(0,1,2), labels=c("Unknown","Male","Female")))
```



```{r load data}


weather <- read_csv("weather_2015.csv")

weather <- select(weather, DATE, PRCP, SNWD, SNOW, TMAX, TMIN)

names(weather) <- tolower(names(weather))

weather <- mutate(weather, ymd = as.Date(date))

weather <- tbl_df(weather)

model <- load("model.RData")

holidays <- read_csv(file="holidays.csv", col_names = FALSE) 

colnames(holidays) <- c("index", "date", "holiday")

holidays <- holidays %>% mutate(ymd = as.Date(date, "%m/%d/%Y")) %>% select(ymd, holiday)


holidays <- holidays %>% mutate(is_holiday = !(is.na(holiday)))



weather$day <- weekdays(weather$ymd)


weather$is_weekend <- (weather$day=="Saturday"|weather$day == "Sunday")



weather <- left_join(weather, holidays)

weather[c("is_holiday")][is.na(weather[c("is_holiday")])] <- FALSE


trips_w_num_trips <- trips %>%
  select(ymd) %>%

  group_by(ymd) %>%

  summarize(num_trips = n())
```


```{r predict}
trips_w_weather <- left_join(weather, trips_w_num_trips)



trips_w_weather <- mutate(trips_w_weather, tmax = tmax*10)



trips_w_weather <- add_predictions(trips_w_weather, lm_fit)

RMSE <- sqrt(mean((trips_w_weather$pred - trips_w_weather$num_trips)^2))

r_sq <- rsquare(lm_fit, trips_w_weather)


RMSE

r_sq

```



```{r plot1}


test %>%

  ggplot() +

  geom_point(aes(x = ymd, y = num_trips)) +

  geom_line(aes(x = ymd, y = pred), color = "blue") +

  xlab("Day") +

  ylab("Number of Rides") +

  scale_y_continuous(label = comma)

```



```{r plot2}



test %>%

  ggplot() +

  geom_point(aes(x = pred, y = num_trips)) +

  xlab("Predicted Rides") +

  ylab("Actual Rides") +

  scale_x_continuous(label = comma) +

  scale_y_continuous(label = comma)



```


